SET XACT_ABORT ON;
BEGIN TRAN;

IF OBJECT_ID(N'dbo.Users',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Users(
  UserId BIGINT IDENTITY PRIMARY KEY, Name NVARCHAR(120) NOT NULL, Email NVARCHAR(254) NOT NULL,
  PasswordHash NVARCHAR(500) NOT NULL, IsActive BIT NOT NULL DEFAULT 1,
  CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_Users_Email UNIQUE(Email));
END;

IF OBJECT_ID(N'dbo.Roles',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Roles(RoleId BIGINT IDENTITY PRIMARY KEY, Name NVARCHAR(60) NOT NULL UNIQUE);
 INSERT dbo.Roles(Name) VALUES('SuperAdmin'),('Admin'),('BusinessOwner'),('Customer'),('Staff'),('Advertiser');
END;

IF OBJECT_ID(N'dbo.UserRoles',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.UserRoles(UserId BIGINT NOT NULL,RoleId BIGINT NOT NULL,CONSTRAINT PK_UserRoles PRIMARY KEY(UserId,RoleId),
  CONSTRAINT FK_UserRoles_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId),
  CONSTRAINT FK_UserRoles_Role FOREIGN KEY(RoleId) REFERENCES dbo.Roles(RoleId));
END;

IF OBJECT_ID(N'dbo.Services',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Services(ServiceId BIGINT IDENTITY PRIMARY KEY,CategoryId BIGINT NULL,Name NVARCHAR(160) NOT NULL,Slug NVARCHAR(180) NOT NULL UNIQUE,Description NVARCHAR(2000) NULL,IsActive BIT NOT NULL DEFAULT 1,CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Services_Category FOREIGN KEY(CategoryId) REFERENCES dbo.Categories(CategoryId));
END;

IF OBJECT_ID(N'dbo.Reviews',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Reviews(ReviewId BIGINT IDENTITY PRIMARY KEY,BusinessId BIGINT NOT NULL,UserId BIGINT NOT NULL,Rating INT NOT NULL,Review NVARCHAR(4000) NULL,IsApproved BIT NOT NULL DEFAULT 0,CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Reviews_Business FOREIGN KEY(BusinessId) REFERENCES dbo.Businesses(BusinessId),CONSTRAINT FK_Reviews_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId),CONSTRAINT CK_Reviews_Rating CHECK(Rating BETWEEN 1 AND 5));
END;

IF OBJECT_ID(N'dbo.Bookings',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Bookings(BookingId BIGINT IDENTITY PRIMARY KEY,BusinessId BIGINT NOT NULL,CustomerId BIGINT NOT NULL,ServiceId BIGINT NULL,BookingDateUtc DATETIME2(3) NOT NULL,Notes NVARCHAR(2000) NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'Pending',CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
  FOREIGN KEY(BusinessId) REFERENCES dbo.Businesses(BusinessId),FOREIGN KEY(CustomerId) REFERENCES dbo.Users(UserId),FOREIGN KEY(ServiceId) REFERENCES dbo.Services(ServiceId));
END;

IF OBJECT_ID(N'dbo.Enquiries',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Enquiries(EnquiryId BIGINT IDENTITY PRIMARY KEY,BusinessId BIGINT NOT NULL,CustomerId BIGINT NOT NULL,Message NVARCHAR(4000) NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'New',CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),FOREIGN KEY(BusinessId) REFERENCES dbo.Businesses(BusinessId),FOREIGN KEY(CustomerId) REFERENCES dbo.Users(UserId));
END;

IF OBJECT_ID(N'dbo.Leads',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Leads(LeadId BIGINT IDENTITY PRIMARY KEY,BusinessId BIGINT NULL,CustomerId BIGINT NULL,Message NVARCHAR(4000) NOT NULL,Status NVARCHAR(30) NOT NULL DEFAULT 'New',CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
END;

IF OBJECT_ID(N'dbo.Advertisements',N'U') IS NULL
BEGIN
 CREATE TABLE dbo.Advertisements(AdvertisementId BIGINT IDENTITY PRIMARY KEY,Title NVARCHAR(200) NOT NULL,ImageUrl NVARCHAR(1000) NULL,TargetUrl NVARCHAR(1000) NULL,CategoryId BIGINT NULL,CityId BIGINT NULL,StartDate DATETIME2(3) NOT NULL,EndDate DATETIME2(3) NOT NULL,IsActive BIT NOT NULL DEFAULT 1,Impressions BIGINT NOT NULL DEFAULT 0,Clicks BIGINT NOT NULL DEFAULT 0,CreatedByUserId BIGINT NULL,CreatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),UpdatedDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME());
END;

CREATE INDEX IF NOT EXISTS IX_Businesses_Location ON dbo.Businesses(Latitude,Longitude,IsActive);
CREATE INDEX IF NOT EXISTS IX_Reviews_Business ON dbo.Reviews(BusinessId,IsApproved,CreatedDate);
CREATE INDEX IF NOT EXISTS IX_Bookings_Customer ON dbo.Bookings(CustomerId,BookingDateUtc);
CREATE INDEX IF NOT EXISTS IX_Enquiries_Customer ON dbo.Enquiries(CustomerId,CreatedDate);
CREATE INDEX IF NOT EXISTS IX_Leads_Business ON dbo.Leads(BusinessId,CreatedDate);
CREATE INDEX IF NOT EXISTS IX_Advertisements_ActiveDates ON dbo.Advertisements(IsActive,StartDate,EndDate);

COMMIT;